name: Deploy Laravel
on:
  push:
    branches:
      - none
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Get the latest code
        uses: actions/checkout@v4
      - name: ğŸ“€ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: ğŸ”‘ Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: ğŸ“¦ Install Laravel Dependencies
        run: composer update --ignore-platform-reqs
      - name: â™¾ï¸ Prepare storage link
        run: chmod -R 775 storage/
      - name: ğŸ”— Generate Laravel storage link
        run: php artisan config:cache && php artisan storage:link && php artisan config:cache
      - name: ğŸ‘®ğŸ» Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: ğŸ§ª Run Laravel Tests
        run: php artisan test
      - name: ğŸ—‚ï¸ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: |
                  .env
                  storage/app/public
                  public/storage
                  public/storage/**
                  database/database.sqlite
                  resources/ionic
                  resources/ionic/**
      - name: ğŸ§¼  Clear server cache
        run: curl -X GET https://maranatha.imedicineapp.com/api/cd/config-cache
      - name: â° Migrate on server
        run: curl -X GET https://maranatha.imedicineapp.com/api/cd/migrate
      - name: ğŸ§¼  Clear server cache
        run: curl -X GET https://maranatha.imedicineapp.com/api/cd/config-cache
