name: Deploy Laravel
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: ğŸ“¦ Install Laravel Dependencies
        run: composer update --ignore-platform-reqs
      - name: ğŸ–¥ï¸ Install Ionic CLI
        run: npm install -g @ionic/cli
      - name: â™¾ï¸ Prepare storage link
        run: chmod -R 775 storage/
      - name: ğŸ”— Generate storage link
        run: php artisan storage:link
      - name: ğŸ‘®ğŸ» Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: ğŸ“¦ Install Ionic Dependencies
        run: cd ionic; ls;
      - name: ğŸ”¨ Build Ionic Project
        run: ionic build --prod; cd ..;
      - name: ğŸ—‚ï¸ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: .env