name: Deploy Laravel
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Get the latest code
        uses: actions/checkout@v2.3.2
      - name: ğŸ“¦ Setup Node.js
        uses: actions/setup-node@master
      - name: ğŸ”‘ Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: ğŸ“¦ Install Laravel Dependencies
        run: composer update --ignore-platform-reqs
      - name: â™¾ï¸ Prepare storage link
        run: chmod -R 775 storage/
      - name: ğŸ”— Generate Laravel storage link
        run: php artisan storage:link && php artisan config:cache
      - name: ğŸ‘®ğŸ» Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: ğŸ§¹ Clean Ionic Source
        run: rm -rf maranatha-sender-native
      - name: ğŸ§ª Run Laravel Tests
        run: php artisan test
      - name: ğŸ—‚ï¸ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: |
                  .env
                  storage/app/public
                  database/database.sqlite
      - name: ğŸ§¼  Clear server cache
        run: curl -X GET https://maranatha.imedicineapp.com/api/cd/config-cache
      - name: â° Migrate on server
        run: curl -X GET https://maranatha.imedicineapp.com/api/cd/migrate
      - name: ğŸ§¼  Clear server cache
        run: curl -X GET https://maranatha.imedicineapp.com/api/cd/config-cache
