name: Integrate
on:
  pull_request:
    branches:
      - main
jobs:
  test_pull_request:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: ğŸ”‘ Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: ğŸ“¦ Install Laravel Dependencies
        run: composer update --ignore-platform-reqs
      - name: â™¾ï¸ Prepare storage link
        run: chmod -R 775 storage/
      - name: ğŸ”— Generate Laravel storage link
        run: php artisan storage:link && php artisan config:cache
      - name: ğŸ‘®ğŸ» Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: ğŸ’» Install Ionic CLI
        run: npm install -g @ionic/cli
      - name: ğŸ“¦ Install Ionic Dependencies
        run: cd ionic && npm install
      - name: ğŸ”¨ Build Ionic Project
        run: npm run build
      - name: ğŸ§ª Run Laravel Tests
        run: php artisan test